# Documentation: https://docs.codecov.io/docs/codecov-yaml

codecov:
    # Avoid "Missing base report"
    # https://github.com/codecov/support/issues/363
    # https://docs.codecov.io/docs/comparing-commits
    allow_coverage_offsets: true

    # Avoid "Please provide the repository token to upload reports via `-t :repository-token`"
    # https://community.codecov.io/t/whitelist-github-action-servers-to-upload-without-a-token/491/10
    # https://github.community/t5/GitHub-Actions/Make-secrets-available-to-builds-of-forks/m-p/42814/highlight/true#M5129
    token: 0ef021c7-2679-4012-b42f-4bed33d99450
