version: 1.0.0.{build}
image: Visual Studio 2017

# prevent the double build when a branch has an active PR
skip_branch_with_pr: true

environment:
  matrix:
    - target_framework: netcoreapp2.1
      is_32bit: False

    - target_framework: netcoreapp2.1
      is_32bit: True

    - target_framework: net472
      is_32bit: False

    - target_framework: net472
      is_32bit: True

    - target_framework: net462
      is_32bit: False

    - target_framework: net462
      is_32bit: True
    
    #- target_framework: mono
    #  is_32bit: False
    #- target_framework: mono
    #  is_32bit: True
    #- target_framework: net47
    #  is_32bit: False
    #- target_framework: net47
    #  is_32bit: True

install:
  - ps: |
        if ($env:target_framework -eq "mono") { 
          if ($env:is_32bit -eq "True") { 
            cinst mono --x86
          } else { 
            cinst mono
          }
        }

        $sdkUrl = "https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.2.105/dotnet-sdk-2.2.105-win-x64.zip"
        Write-Host "Installing .NET Core"
        $env:DOTNET_INSTALL_DIR = "$path/.dotnetsdk"
        New-Item -Type Directory $env:DOTNET_INSTALL_DIR -Force | Out-Null
        (New-Object System.Net.WebClient).DownloadFile($sdkUrl, "dotnet.zip")
        Write-Host "Unzipping to $env:DOTNET_INSTALL_DIR"
        Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory("dotnet.zip", $env:DOTNET_INSTALL_DIR)

before_build:
  - git submodule -q update --init
  - cmd: dotnet --info
  
build_script:
- cmd: build.cmd

test_script:
- ps: .\run-tests.ps1 $env:target_framework $env:is_32bit

after_test:
  - cmd: appveyor PushArtifact "artifacts\SixLabors.ImageSharp.%APPVEYOR_BUILD_VERSION%.nupkg"
  - cmd: appveyor PushArtifact "artifacts\SixLabors.ImageSharp.Drawing.%APPVEYOR_BUILD_VERSION%.nupkg"

deploy:
    # MyGet Deployment for builds & releases
  - provider: NuGet
    server: https://www.myget.org/F/sixlabors/api/v2/package
    symbol_server: https://www.myget.org/F/sixlabors/symbols/api/v2/package
    api_key:
      secure: V/lEHP0UeMWIpWd0fiNlY2IgbCnJKQlGdRksECdJbOBdaE20Fl0RNL7WyqHe02o4
    artifact: /.*\.nupkg/
    on:
      branch: master